### ISSUE TITLE
Repeater functionality

### ISSUE THREAD

**Issue by rawdamedia** [rawdamedia/quoil#1]
Is there a better way of doing this?  In particular:
- is there a way to have this run separate from a particular shell session, so that if I initiate it by remoting into a machine via SSH, I can leave it to run without having to maintain the shell connection?  
- Maybe there already is a scheduler framework for Elixir?  
- Should I just use the system scheduler mechanism, at the cost of being less portable between linux and mac?

**Comment by madlep** [comment]
To run it without requiring an SSH connection there are a few options.

If it's a run-once till finish, then shut down job, I'd handle this with the `screen` utility - it starts a sub shell where you run your command. You can detach from it and disconnect. It will keep running in the background. You can reconnect again if needed later on a new SSH session.

If it's a daemon process that needs to run indefinitely in the background, I'd use `upstart` or `init` or whatever the flavour of linux you're using has for maintaining system jobs that need to be kept up. It will restart if they crash, or if the OS reboots.
