### ISSUE TITLE
Testing functions that contain System.halt

### ISSUE THREAD

**Issue by rawdamedia** [rawdamedia/quoil#2]
I know this is taking testing to ridiculous extremes for this app, but the point is to learn a way of doing things...
Is there a way of stubbing out `System.halt` in `Quoil.CLI.terminate_early?` only for the tests, without inserting conditional code into the actual function that checks for the mix environment variable? (I want to keep the actual function cleaner, without introducing testing-only code into the function itself)

**Comment by madlep** [comment]
I'd have a look at mocking libraries like https://github.com/jjh42/mock

So you could do something like

```elixir
test "test_name" do
  with_mock System, [halt: fn(_url) -> nil end] do
    main(["--help"])
    assert called System.halt(0)
  end
end
```
